"""Named label spaces used by bundled auto-labeling models.

The model catalog refers to these by name so the same COCO vocabulary is not
copied into every YAML entry.  The sparse 91-slot form is the tensor layout
used by official RF-DETR exports; ``None`` entries are dataset gaps and must
never be presented as classes.
"""

from __future__ import annotations

from collections.abc import Sequence

COCO_80: tuple[str, ...] = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

_COCO_91_IDS = (
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    27,
    28,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    67,
    70,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
)

_coco_91: list[str | None] = [None] * 91
for _class_name, _category_id in zip(COCO_80, _COCO_91_IDS, strict=True):
    _coco_91[_category_id] = _class_name
COCO_91: tuple[str | None, ...] = tuple(_coco_91)

LABEL_SPACES: dict[str, Sequence[str | None]] = {
    "coco80": COCO_80,
    "coco91": COCO_91,
}


def resolve_label_space(name: str) -> tuple[str | None, ...]:
    """Return a known immutable label layout or reject the catalog entry."""
    try:
        return tuple(LABEL_SPACES[name])
    except KeyError as error:
        raise ValueError(f"Unknown auto-labeling label space: {name}") from error


__all__ = ["COCO_80", "COCO_91", "LABEL_SPACES", "resolve_label_space"]
