; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AnyLearning"
; MyAppVersion comes from anylearning/app_info.py via build_app.sh.
; Run build_app.sh before ISCC so installer_version.iss exists.
#include "installer_version.iss"
#define MyAppPublisher "Neural Research Lab NRL.ai"
#define MyAppURL "https://www.nrl.ai"
#define MyAppExeName "AnyLearning.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".anyl"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CEF48AA0-16F6-4A5D-88E3-AEBBE51E55AA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=AnyLearning-GPU-Windows-Setup-{#MyAppVersion}
; The agreement the user accepts to install. Inno shows exactly one licence
; page, so this is the one that needs consent; the third-party notices ship
; inside the app and are readable from Settings -> About.
LicenseFile=LICENSE
; Shown on its own page before that, so the notices are still put in front of
; whoever installs it.
InfoBeforeFile=LICENSES.md
SetupIconFile=app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
DiskSpanning=yes
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "AnyLearning.App\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "AnyLearning.App\*"; DestDir: "{app}"; Excludes: "__pycache__,__pycache__\*,*.pyc"; Flags: ignoreversion recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Check: NeedsAddPath(ExpandConstant('{app}'))

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: postinstall skipifsilent

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;

procedure RemoveAppFromMachinePath();
var
  OrigPath: string;
  WrappedPath: string;
  WrappedApp: string;
  MatchAt: Integer;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    exit;
  end;

  { The registry entry above appends exactly one unquoted app-directory segment. Wrap
    both strings in semicolons so removing it cannot match a prefix of another
    directory (for example, AnyLearning-Tools). Pos is case-sensitive, while
    Windows paths are not, so search a lower-cased copy and delete from the
    original value at the same character offset. }
  WrappedPath := ';' + OrigPath + ';';
  WrappedApp := ';' + ExpandConstant('{app}') + ';';
  MatchAt := Pos(Lowercase(WrappedApp), Lowercase(WrappedPath));
  while MatchAt > 0 do begin
    { Keep the pattern's first semicolon. It remains the separator between the
      entries on either side after the directory and trailing semicolon go. }
    Delete(WrappedPath, MatchAt + 1, Length(WrappedApp) - 1);
    MatchAt := Pos(Lowercase(WrappedApp), Lowercase(WrappedPath));
  end;

  if (Length(WrappedPath) > 0) and (WrappedPath[1] = ';') then
    Delete(WrappedPath, 1, 1);
  if (Length(WrappedPath) > 0) and
     (WrappedPath[Length(WrappedPath)] = ';') then
    Delete(WrappedPath, Length(WrappedPath), 1);

  RegWriteExpandStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', WrappedPath);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
    RemoveAppFromMachinePath();
end;
