#! /bin/bash

# Fail on the first error. Without this the script sails past a failed Nuitka
# run -- straight into patch_libtorch.py and the rename steps -- and exits 0, so
# a build that produced nothing looks like it succeeded.
set -euo pipefail

# Editing this file while a build is running used to break the build. Bash reads
# a script incrementally as it executes, so changing it under a running build
# shifts the offsets it is still reading from: an edit an hour in produced
#     build_app.sh: line 292: ends: command not found
# as bash resumed in the middle of a comment and ran a word out of it. The whole
# body is wrapped in `main()` now, and bash parses a function completely before
# running any of it, so the running build holds its own copy and an edit reaches
# only the next one. Do not unwrap it; that is what the wrapper is for.
#
# And do not start a second one in this directory. Two runs share app.build and
# the second dies with
#     AssertionError: app.build/module.PIL.c
# because Nuitka refuses to overwrite generated source the other just wrote.
# Two ways of checking that lie to you, both tried here:
#   pgrep -f "python -m nuitka"  matches the shell running the pgrep, so it
#                                always finds "something".
#   grep -- " -m nuitka"         finds nothing while Nuitka is at 96% CPU,
#                                because it is started as
#                                `python -X frozen_modules=off -S .../nuitka/__main__.py`.
# Grep for `nuitka/__main__.py`, or just look at `ps -ef | grep build_app`.

main() {
# Read the version from the one place that defines it, rather than repeating it
# here. Kept as a grep so it works before the package is importable.
VERSION="$(sed -n 's/^__version__ = "\(.*\)"/\1/p' anylearning/app_info.py)"
if [ -z "$VERSION" ]; then
    echo "Could not read __version__ from anylearning/app_info.py" >&2
    exit 1
fi
echo "Building AnyLearning ${VERSION}"

# Inno Setup cannot read Python, so hand it the same value through a generated
# include. Both .iss scripts #include this file.
cat > installer_version.iss <<EOF
; Generated by build_app.sh -- do not edit.
; The version comes from anylearning/app_info.py.
#define MyAppVersion "${VERSION}"
EOF

# Stamp packaged builds so diagnostics can distinguish them from a checkout.
# The generated file is removed when the build exits.
NUITKA_OUTPUT_DIR=
cat > anylearning/build_stamp.py <<STAMP
# Generated by build_app.sh -- not committed, not present in a checkout.
IS_RELEASE_BUILD = True
STAMP
# INT and TERM as well as EXIT: bash does not run an EXIT trap when the shell
# is killed by an untrapped signal, and a build interrupted with Ctrl-C or
# `kill` is the common case. Leaving the stamp turns the checkout into a
# release build until someone notices.
trap 'rm -f anylearning/build_stamp.py' EXIT INT TERM

# Remove build folder. A twin clears only its own: deleting app.dist here would
# destroy the release tree it is meant to be compared against, which is the one
# thing a verification build must not do.
if [ -n "$NUITKA_OUTPUT_DIR" ]; then
    rm -rf "$NUITKA_OUTPUT_DIR"
else
    rm -rf app.build
    rm -rf app.dist
    rm -rf AnyLearning.App # Windows
    rm -rf AnyLearning.app # macOS
fi

# Uninstall torchaudio to avoid bug
pip uninstall -y torchaudio || true



# Pick the right OpenCV *variant* for the platform. No version is given here on
# purpose: setup.py owns the version range, and the exact 4.10.0.84 that used to
# be pinned in this script silently downgraded the environment below that range
# right before packaging.
echo "Installing opencv-python..."
echo "OS: $OSTYPE"
if [[ "$OSTYPE" == "msys"* ]] || [[ "$OSTYPE" == "win"* ]]; then
    pip uninstall -y opencv-contrib-python || true
    pip uninstall -y opencv-python || true
    pip install "opencv-python>=4.11,<6"
else
    pip install "opencv-python-headless>=4.11,<6"
fi

# Rebuild the frontend whenever a source file is newer than the export, not
# merely when the export is missing. The previous check meant that editing the
# UI and then packaging silently shipped whatever export happened to be lying
# around -- a build begun at 12:00 embedded a frontend exported at 17:41 the
# day before, without any of that morning's fixes, and nothing said so.
needs_frontend=0
if [ ! -d "anylearning/frontend-dist" ]; then
    echo "Frontend dist does not exist."
    needs_frontend=1
elif [ -n "$(find frontend/src frontend/public frontend/package.json \
        -newer anylearning/frontend-dist -print -quit 2>/dev/null)" ]; then
    echo "Frontend sources are newer than the export."
    needs_frontend=1
fi

if [ "$needs_frontend" = 1 ]; then
    echo "Building frontend..."
    bash build_frontend.sh
else
    echo "Frontend export is up to date."
fi

# Build app
# Snapshot the export and package *that*. Nuitka lists the data files up front
# but copies them at the very end, so anything that regenerates frontend-dist
# during the build -- another build_frontend.sh, the desktop app -- invalidates
# the list it is holding. That killed a build after an hour of compiling:
#
#   FileNotFoundError: anylearning/frontend-dist/_next/static/<old-build-id>/_buildManifest.js
#
# Next writes a fresh build id per export, so every filename changes at once.
FRONTEND_SNAPSHOT="build-frontend-dist"
rm -rf "$FRONTEND_SNAPSHOT"
cp -r anylearning/frontend-dist "$FRONTEND_SNAPSHOT"
echo "Snapshotted frontend export to ${FRONTEND_SNAPSHOT}"

# detectron2's extension records its torch dependencies as @rpath/libc10.dylib
# and friends, and carries an rpath a pip-installed torch does not satisfy.
# Nothing notices at runtime -- torch is imported first, so the references bind
# to images already in memory -- but Nuitka has to resolve them on disk, and
# every macOS build so far has died right there. No-op off macOS.
python patch_detectron2_macos.py
python patch_catboost_macos.py

# The options are an array so the explanations can be ordinary `#` comments.
# They used to be backtick-comments inside the command, where an apostrophe
# opens a quote the shell then hunts for across the following lines: adding a
# comment containing one silently turned the rest of the options into
# commands, and the build carried on without them. The flags below are the
# difference between a binary that works and one that segfaults, so they are
# not worth losing to an apostrophe.
NUITKA_ARGS=(
    --include-data-dir="$FRONTEND_SNAPSHOT"=anylearning/frontend-dist
    --include-data-dir=anylearning/training/configs=anylearning/training/configs
    --include-data-dir=anylearning/configs=anylearning/configs
    --include-data-dir=anylearning/models=anylearning/models
    # Third-party licence notices. MIT, BSD and Apache 2.0 all require the
    # notice to ship with the binary, so this is a legal artefact rather
    # than documentation -- anylearning/legal.py looks for it here first.
    --include-data-files=LICENSES.md=anylearning/LICENSES.md
    # The project license, shown by the installer and readable from Settings.
    --include-data-files=LICENSE=anylearning/LICENSE
    # Which weights ship and what their licences allow. Note this is not
    # docs/model_license_policy.md, which is the rule we apply when choosing a
    # model: that one names repository paths and models we rejected, and has no
    # business in the end-user Settings screen.
    --include-data-files=MODEL_LICENCES.md=anylearning/MODEL_LICENCES.md
    # Alembic reads env.py and its revisions from disk by path, so compiling
    # them into the binary is not enough -- they have to exist as files.
    #
    # --include-raw-dir, not --include-data-dir: the latter SILENTLY SKIPS
    # .py files, on the assumption that anything importable is being compiled
    # instead. That shipped a migrations folder holding only README and
    # script.py.mako, so the packaged app could not migrate a database it had
    # created itself -- and MigrationManager catches its own errors, so
    # nothing said so. Nuitka's author recommends exactly this (a raw dir, or
    # an explicit *.py pattern): github.com/Nuitka/Nuitka/issues/3270.
    #
    # Verified in a throwaway build that alembic can not only find but RUN a
    # revision from inside a frozen binary -- it created the table and wrote
    # the stamp. Shipping the file and importing it at runtime are different
    # questions, and only the second one matters.
    --include-raw-dir=anylearning/migrations=anylearning/migrations
    # Pretrained weights, so the first training run of each architecture does
    # not download its backbone. An app sold on working offline was fetching
    # ShuffleNetV2, a torchvision ResNet, an smp encoder and up to 500 MB of
    # Mask R-CNN the first time each type was trained -- and failing, on a
    # machine with no network, after the dataset had already been prepared.
    # Run fetch_weights.py before building; the caches are pointed here by
    # anylearning/weights.py.
    --include-data-dir=weights=anylearning/weights
    --follow-imports
    --standalone
    --include-module=anylearning.app
    --macos-app-icon=app_icon.png
    --windows-icon-from-ico=app_icon.ico
    --windows-console-mode=disable
    --company-name=AnyLearning
    --product-name=AnyLearning
    --file-version=$VERSION
    --product-version=$VERSION
    --file-description="AnyLearning"
    --module-parameter=torch-disable-jit=yes
    # Nuitka otherwise derives every macOS identity field from the input file
    # name (`app`): the bundle then reports identifier `app`, display name
    # `app`, and version `1.0`, even when the executable reports the configured
    # product version.
    # Keep this stable before ad-hoc or Developer ID signing; changing an
    # Info.plist after signing invalidates the bundle seal.
    --macos-signed-app-name=ai.nrl.anylearning
    --macos-app-name=AnyLearning
    --macos-app-version=$VERSION
    # torch._dynamo used to be excluded here, on the reasoning that nothing
    # calls torch.compile and that it dodged a Nuitka 2.8.10 optimiser crash.
    # That shipped a binary which died on startup:
    #   ImportError: Module 'torch._dynamo' was actively excluded
    #   ... torchvision/ops/roi_align.py line 7
    # torchvision.ops imports it at module level, and torchvision.ops is on the
    # import path of every trainer. "We never call it" was not the same as
    # "nothing imports it". Re-test against the pinned Nuitka before excluding
    # either of these again -- and check the built binary actually starts.
    --macos-create-app-bundle
    --enable-plugin=no-qt
    # detectron2's PicklableWrapper serialises functions with cloudpickle to
    # hand them to dataloader workers, so instance segmentation exercises it at
    # runtime. Without dill-compat, cloudpickle cannot serialise Nuitka-compiled
    # functions and that path breaks only in the packaged app.
    --enable-plugin=dill-compat
    # scipy's vendored array_api_compat builds its modules with clone_module(),
    # which Nuitka cannot resolve statically. In the full application it dropped
    # scipy._external.array_api_compat.numpy.fft -- compiling the sibling
    # modules but denying that one -- and the binary then segfaulted during
    # startup rather than raising ImportError, with no message at all. A build
    # of scipy on its own does not reproduce it, so the module graph matters;
    # name the package explicitly rather than rely on the analysis.
    --include-package=scipy._external.array_api_compat
    # detectron2 loads its Mask R-CNN configs from model_zoo/configs, which are
    # package data rather than importable modules -- Nuitka does not collect
    # them, so instance segmentation failed at training with
    # "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml not available in
    # Model Zoo!" even though detectron2 itself imported fine.
    --include-package-data=detectron2
    # RF-DETR reads its DINOv2 backbone architecture from JSON shipped inside
    # the package -- rfdetr/models/backbone/dinov2_configs/*.json -- on every
    # model construction, training and inference alike. Same shape of problem
    # as detectron2's model zoo above: Nuitka compiles the modules and collects
    # none of the data, so `import rfdetr` succeeds and building a model fails.
    --include-package-data=rfdetr
    # The trainer never asks rfdetr to import a variant it does not ship, but
    # rfdetr resolves its config classes through getattr on rfdetr.config, and
    # the trainer itself is only imported lazily -- neither is something
    # Nuitka's static analysis can follow to the modules underneath.
    --include-package=rfdetr
    --include-package=anylearning.training.trainers
    # RF-DETR prediction imports supervision lazily. supervision imports PyAV,
    # whose compiled extension modules import av.utils through Cython rather
    # than a Python import statement. Nuitka followed the rest of PyAV but
    # omitted this one module, so a packaged keypoint model could train, export
    # and register, then every inference request failed with
    # "No module named 'av.utils'". Name the hidden dependency explicitly.
    --include-module=av.utils
    # Every torch.onnx.export call passes dynamo=False, so the dynamo exporter
    # -- and onnxscript with it -- is never reached. onnxscript cannot work in
    # a compiled binary at all: its @script decorator calls inspect.getsource()
    # to parse a function's AST, and compiled code has no source, so it raises
    # "Decorator script does not work on dynamically compiled function".
    # torch.onnx does not import it eagerly, so it is left out entirely.
    # Nuitka's bundled config for torch sets 'triton': 'ignore', and its
    # deployment guard turns any use of an excluded module into a hard error.
    # torch probes for triton during lazy CUDA init and copes fine when it is
    # absent -- but the guard raised instead, so every GPU training run died
    # with "CUDA call failed lazily at initialization". This turns the guard
    # off so the probe fails the way torch expects. Bundling triton itself
    # would add hundreds of MB for a code path the app never takes.
    #
    # The cost: a genuinely missing module now surfaces as an ordinary
    # ImportError rather than a message naming the build flag. That is what
    # smoke_test_build.sh and smoke_test_training.py are for.
    --no-deployment-flag=excluded-module-usage
    # Lists what was and was not included. Reach for this when the binary dies
    # on an import: finding the last module in a PYTHONVERBOSE trace costs an
    # hour-long rebuild per guess, and the report is free.
    --report=compilation-report.xml
    # Escape hatch for CI, which uses a standard CPython rather than Anaconda's
    # and so needs --static-libpython=no, plus --assume-yes-for-downloads so the
    # build never blocks on an interactive prompt.
    ${NUITKA_EXTRA_ARGS:-}
)

# mediapipe's Python modules are compiled in, but everything they call lives in
# a 100 MB native library the package dlopens from its own directory --
# `<app>/mediapipe/tasks/c/libmediapipe.{so,dylib,dll}`. Nuitka collects no data
# for the package, so that path did not exist and *uploading an image to a
# handpose project* failed with a dlopen error naming three paths that are all
# absent.
#
# It went unnoticed because handpose is the one column `--self-test` cannot
# generate -- it needs real hand landmarks -- so this code path had never run
# inside a packaged build at all. Found by feature_test.py on macOS, and Linux
# was missing it too.
#
# The library is located by asking mediapipe where it is, rather than guessing a
# site-packages layout, and named per platform because the extension differs.
MEDIAPIPE_DATA=$(python - <<'PY'
import pathlib
import sys

try:
    import mediapipe
except Exception:  # noqa: BLE001 -- a build without it is a build without handpose
    sys.exit(0)

native = pathlib.Path(mediapipe.__file__).parent / "tasks" / "c"
for name in ("libmediapipe.so", "libmediapipe.dylib", "libmediapipe.dll", "mediapipe.dll"):
    library = native / name
    if library.is_file():
        print(f"{library}=mediapipe/tasks/c/{name}")
        break
PY
)
if [ -n "$MEDIAPIPE_DATA" ]; then
    # Explicitly, not through --include-package-data: that option is documented
    # to collect data files, and a shared library is not one of them.
    NUITKA_ARGS+=(--include-data-files="$MEDIAPIPE_DATA")
    # And the small files beside it -- the metadata schemas and the landmark
    # label lists the tasks API reads.
    NUITKA_ARGS+=(--include-package-data=mediapipe)
    echo "Bundling mediapipe native library: ${MEDIAPIPE_DATA%%=*}"
else
    echo "WARNING: mediapipe not found; handpose will not work in this build" >&2
fi

# --include-raw-dir copies the migrations directory as it is, so a stale
# __pycache__ ends up inside the artefact. Compiled bytecode from whichever
# interpreter last ran here is not part of the release.
find anylearning/migrations -name __pycache__ -type d -prune -exec rm -rf {} + 2>/dev/null || true

if [ -n "$NUITKA_OUTPUT_DIR" ]; then
    NUITKA_ARGS+=(--output-dir="$NUITKA_OUTPUT_DIR")
fi

python -m nuitka "${NUITKA_ARGS[@]}" anylearning/app.py

# Patch libtorch libraries, in whichever tree Nuitka just wrote
python patch_libtorch.py ${NUITKA_OUTPUT_DIR:+"$NUITKA_OUTPUT_DIR"}

# Rename app.app to AnyLearning.app
if [[ "$OSTYPE" == "darwin"* ]] ; then
    rm -rf AnyLearning.app
    mv app.app AnyLearning.app
fi

# Rename app.exe to AnyLearning.exe on Windows
if [[ "$OSTYPE" == "msys"* ]] || [[ "$OSTYPE" == "win"* ]]; then
    mv app.dist/app.exe app.dist/AnyLearning.exe
    mv app.dist/ AnyLearning.App/
fi
}

main "$@"
