save_dir: workspace/handpose

data:
  train:
    annotation_path: /path/to/train
    classes_names: []
    num_workers: 3
    batch_size: 8
  val:
    annotation_path: /path/to/val
    class_names: []
    num_workers: 3
    batch_size: 8
  test:
    annotation_path: /path/to/test
    class_names: []
    num_workers: 3
    batch_size: 8

models:
  arch:
    name: MLPMedium
    backbone:
      hidden_layers: 6
      hidden_units: [63, 128, 256, 256, 256, 256]
      dropout_rate: 0.5
      activation: Relu
    head:
      name: MLPMediumHead
      output_units: 2 # This should be change to match your problem
      dropout_rate: 0.3
      activation: Relu

schedule:
  epochs: 500
  optimizer:
    name: AdamW
    lr: 1.0e-4
    weight_decay: 0.01
    betas: [0.9, 0.999]
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
