"""Building a labelled project the way the app does, over its own API.

Everything here goes through the same endpoints the UI calls -- create the
project, upload a zip per subset, then label what came back. Writing rows
straight into the database would be shorter and would test less: the routers,
the per-project database, the upload's background processing and the annotation
format are all on the path a real project takes, and all of them can break in a
packaged build.
"""

from __future__ import annotations

import time
import urllib.request
import uuid

from anylearning.selftest import synthetic
from anylearning.selftest.driver import api

# Project type -> the kind of annotation its trainer expects. Handpose is
# absent on purpose: its trainer reads hand landmarks out of the image with
# mediapipe, and no drawn shape produces those, so a synthetic project would
# train on nothing at all. It is covered by running against real data.
KINDS = {
    "Image Classification": "classification",
    "Object Detection": "detection",
    "Image Segmentation": "segmentation",
    "Instance Segmentation": "segmentation",
    "Keypoint Detection": "keypoint",
}

CLASS_NAMES = ("circle", "square", "triangle")


def _upload(
    base: str, project_id: int, subset: int, archive: bytes, token=None
) -> None:
    """POST a zip to upload_data as multipart, then wait for it to be processed."""
    boundary = uuid.uuid4().hex
    body = b"".join(
        [
            f"--{boundary}\r\n".encode(),
            b'Content-Disposition: form-data; name="file"; filename="data.zip"\r\n',
            b"Content-Type: application/zip\r\n\r\n",
            archive,
            f"\r\n--{boundary}--\r\n".encode(),
        ]
    )
    request = urllib.request.Request(
        f"{base}/api/projects/{project_id}/upload_data?subset={subset}",
        data=body,
        headers={
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            **({"Authorization": f"Bearer {token}"} if token else {}),
        },
    )
    with urllib.request.urlopen(request, timeout=120):
        pass

    # The endpoint returns as soon as the background task is queued.
    deadline = time.time() + 300
    while time.time() < deadline:
        status = (
            api(base, f"/api/projects/{project_id}/upload_status", token=token) or {}
        )
        if status.get("status") in {"completed", "failed"}:
            if status.get("status") == "failed":
                raise RuntimeError(f"upload failed: {status}")
            return
        time.sleep(1)
    raise RuntimeError("upload never finished")


def _label(
    base: str, project_id: int, annotations: dict, class_names, token=None
) -> int:
    """Attach the annotation each uploaded image was drawn to have."""
    labelled = 0
    for subset in synthetic.SUBSETS:
        page = (
            api(
                base,
                f"/api/projects/{project_id}/data_items?subset={subset}&limit=1000",
                token=token,
            )
            or {}
        )
        for item in page.get("data_items", []):
            wanted = annotations.get(item.get("original_name") or item.get("path"))
            if not wanted:
                continue
            if "class_name" in wanted:
                api(
                    base,
                    f"/api/projects/{project_id}/data_items/{item['id']}/class_id",
                    {"class_id": class_names.index(wanted["class_name"])},
                    token=token,
                )
            else:
                api(
                    base,
                    f"/api/projects/{project_id}/data_items/{item['id']}/set_annotation",
                    wanted["shapes"],
                    token=token,
                )
            labelled += 1
    return labelled


def build(
    base: str, project_type: str, per_subset: int, size: int, seed: int, token=None
) -> dict:
    """Create a small labelled project of `project_type`. Returns it."""
    kind = KINDS[project_type]
    class_names = list(CLASS_NAMES)

    project = api(
        base,
        "/api/projects",
        {
            "name": f"Self-test {project_type}",
            "description": "Generated by --self-test; safe to delete.",
            "type": project_type,
            "labels": synthetic.labels_for(class_names),
        },
        token=token,
    )
    project_id = project["id"]

    total_labelled = 0
    for offset, subset in enumerate(synthetic.SUBSETS):
        archive, annotations = synthetic.build_subset(
            kind, per_subset, size, seed + offset, class_names
        )
        _upload(base, project_id, subset, archive, token=token)
        total_labelled += _label(
            base, project_id, annotations, class_names, token=token
        )

    if not total_labelled:
        raise RuntimeError("uploaded images but labelled none")
    project["labelled"] = total_labelled
    return project
