- name: "sam2_hiera_small_20240803"
  display_name: Segment Anything 2 (Hiera-Small)
  type: segment_anything
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_small.zip
- name: "sam2_hiera_tiny_20240803"
  display_name: Segment Anything 2 (Hiera-Tiny)
  type: segment_anything
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_tiny.zip
- name: "mobile_sam_20230629"
  display_name: MobileSAM
  type: segment_anything
  download_url: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/mobile_sam_20230629.zip
- name: "sam2_hiera_base_plus_20240803"
  display_name: Segment Anything 2 (Hiera-Base+)
  type: segment_anything
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_base_plus.zip
- name: "sam2_hiera_large_20240803"
  display_name: Segment Anything 2 (Hiera-Large)
  type: segment_anything
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_large.zip
